### ISSUE TITLE
Pubkey importing

### ISSUE THREAD

**Issue by MoeMorox** [irssiconnectbot/irssiconnectbot#28] opened 2011-12-21 16:38 UTC
Hello,

I created a pubkey with PuTTYgen.exe, it works fine with PuTTY and my Debian vps.
Now I want to import the key, but it says there's an error at parsing the key.
What file do I have to use?
I tried it with my privat key file and with the public key file, both doesn't work.

Please help me,

moritz

**Comment by NullOrNaN** [comment] 2012-02-06 02:33
This is not a bug in this app, rather a stupid move made by Putty, it wants your private key, but putty doesn't make an an openssh compatible private key, only the public key, which can only be ready by Putty. So sadly, unless the developer elects to write special code just for this, then you will be out of luck.

**Comment by woltage** [comment] 2012-02-11 22:37
http://www.youtube.com/watch?v=i0wBmC-5Vu0

Works. Won't fix.

**Closed as completed by woltage** 2012-02-11 22:37 UTC
